apiVersion: v1
kind: Service
metadata:
  labels:
    app: case-api
  name: case-api
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    app: case-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: case-api
  name: case-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: case-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: case-api
    spec:
      containers:
      - image: wyattwalter/case-api:eaf7eb8ee0b526c12ae7bc813e4f982d202c4c66
        name: case-api
        command: ["yarn", "start"]
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: case-api
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/alternating-caps
        backend:
          serviceName: case-api
          servicePort: 80
