apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
patches:
  - argocd-config.yaml
#patchesJson6902:
#  - target:
#      version: v1
#      kind: Service
#      name: argocd-server
#    patch: |-
#      - op: replace
#        path: /spec/type
#        value: LoadBalancer
#      - op: replace
#        path: /spec/ports/0/port
#        value: 8080
#      - op: replace
#        path: /spec/ports/1/port
#        value: 8443