---
repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: "kubernetes-incubator"
  url: "https://charts.helm.sh/incubator"
- name: "argo"
  url: "https://argoproj.github.io/argo-helm"
- name: "1password"
  url: "https://1password.github.io/connect-helm-charts"
- name: oauth2-proxy
  url: "https://oauth2-proxy.github.io/manifests"
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

environments:
  default:
    values:
    - domain: local.ycloud.rocks
    - default_issuer: selfsigned
    - ingress_enabled: false
    - env-override.yaml

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 'v1.7.2'
  wait: true
  set:
  - name: installCRDs
    value: true

- name: 'cert-manager-issuers'
  needs: ['cert-manager/cert-manager', '1password/1password']
  chart: "kubernetes-incubator/raw"
  namespace: "cert-manager"
  cleanupOnFail: true
  labels:
    component: "cert-manager"
    namespace: "cert-manager"
  values:
  - resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned
      spec:
        selfSigned: {}

- name: 1password
  needs: ['cert-manager/cert-manager']
  namespace: 1password
  chart: 1password/connect
  version: '1.7.1'
  wait: true
  timeout: 120
  values:
  - connect:
      credentials: {{ requiredEnv "ONEPASSWORD_CREDENTIALS" | toYaml }}
  - operator:
      create: true
      roleBinding:
        create: true
      serviceAccount:
        create: true
      watchNamespace: []
      token:
        value: {{ requiredEnv "ONEPASSWORD_TOKEN" | quote }}

- name: ingress-nginx
  needs: ['cert-manager/cert-manager']
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: '4.0.18'
  installed: {{ .Values.ingress_enabled }}
  values:
  - controller:
      metrics:
        enabled: true

- name: argocd
  needs: ['cert-manager/cert-manager']
  namespace: argocd
  chart: argo/argo-cd
  version: '4.2.2'
  values:
  - server:
      certificate:
        enabled: true
        domain: "argocd.{{ .Values.domain }}"
        issuer:
          kind: ClusterIssuer
          name: {{ .Values.default_issuer }}
      extraArgs:
      - --insecure
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: {{ .Values.default_issuer }}
        enabled: true
        https: true
        ingressClassName: nginx
        hosts:
        - argocd.{{ .Values.domain }}
        tls:
        - hosts:
          - argocd.{{ .Values.domain }}
          secretName: argocd-cert
