name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: run pre-check on instance
    steps:
    - uses: actions/checkout@v2
    - name: asdf_install
      uses: asdf-vm/actions/install@v1
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: enable minikube addons
      run: |
        minikube addons enable ingress
        minikube addons enable ingress-dns
    - name: run pre-check
      run: make pre-check
